### ISSUE TITLE
Winners Tab

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1327]
At the end of phases save a snapshot of the winners. Like, if we have a phase that never ends we want to save a snapshot of the winners because people may continue submitting to that phase.
- [ ] Manually editable? Can you expand on that @madclam 
- [ ] Doesn't appear until all submissions are marked 'Finished' ??
- [ ] Show every submission by default, but it'd be nice to edit to top 5 or something
- [ ] Tabs for each phase (like results page, just called Winners) -- results frozen

**Comment by madclam** [comment]
By "end of phase", we mean either:
- true end-of-phase date
- start of phase it is feeding into with automatic migration

**Comment by ckcollab** [comment]
Can be made simpler if we disable leaderboard when next phase starts?

**Comment by FlavioAlexander** [comment]
For instance, If we have a phase marked as a "never_end_phase" Once the next phase begins, we could disable the Leaderboard and not allow them to add any new submission to the Leaderboard. Probably some flag is needed to check whether the next phase is running or not. Since "automatic migration" migrates the submissions that are on the Leaderboard, by this approach; we should not face any issue. Having a winner tab is almost the same as the leaderboard. What are your thoughts? @ckcollab @madclam

**Comment by ErickWa** [comment]
Hi @madclam , I think what Flavio's done here is sufficient to meet most of the requirements. Can you check and let us know if you see any gaps?
