### ISSUE TITLE
Changes to competition (using "edit" feature in web interface) not being saved

### ISSUE THREAD

**Issue by AishwaryaAgrawal** [codalab/codalab-competitions#1524]
I tried editing the competitions and found that the changes are still not being saved. Using the admin "Edit" feature in the web interface, I edited the title of the competition from "VQA Real Image Challenge (Open-Ended)" to "Visual Question Answering Real Image Challenge (Open-Ended)" and then clicked "submit". The updated page (yaml file) showed the edited title ("Visual Question Answering Real Image Challenge (Open-Ended)") but then when I navigate to the competition page, the title does not get updated. When I click on the "Edit" button again, it does not show my changes.

**Comment by FlavioAlexander** [comment]
@AishwaryaAgrawal I am closing this issue as we already found what the problem was. Competition was created with an invalid key, and it can't be changed since it is related with your score system. I will probably need to create a new ticket to somehow validate the key before a competition is created.
