### ISSUE TITLE
Program metadata is not available

### ISSUE THREAD

**Issue by spirinus** [codalab/codalab-competitions#1578]
I use the DEMO zip archive with "ada" and "arcene" datasets. With the default "Example_competition_bundle" the system works fine. It correctly creates a competition and participants can successfully upload their solutions without any errors.

However, when I try to remove the files associated with one dataset (e.g. "arcene") from input.zip, from ref_test.zip, from ref_valid.zip and from sample_submission.zip, I experience problems. Specifically, the competition is created correctly but I get an error when I try to "Participate" by uploading a submission. See the error log below:

```
Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 285, in run
    raise Exception("Program metadata is not available.")
Exception: Program metadata is not available.
```

It seems very strange since the only change that I make to the default "Example_competition_bundle" is the removal of one of the two sample datasets. 

What might be wrong here? @madclam @FlavioAlexander @ckcollab @cpoulain Thanks!

**Comment by ckcollab** [comment]
Your zip file is not formatted properly, I believe. Do you have a metadata file in the right place? Haven't worked on this project in a while, forget how it's supposed to look and the example repo seems to have been removed?

**Comment by Spirinus** [comment]
It must be in the right place since the default version works like a charm. The problem happens when I remove all files associated with one data set. I don't touch any metadata files though. Here is the link to the DEMO competition with "arcene" data set removed on the test server: https://competitions-test.codalab.org/competitions/1181?secret_key=292726de-6be5-4c9b-a5d4-68a808310a80

And here is the link to the DEMO.zip: https://drive.google.com/open?id=0BwJWuPPYsmZiYmgzbUNldDBYV1JWZ3BZSWZpR2lFNFo1ZjZN

**Comment by madclam** [comment]
The problem was probably that the zip file included a sub-directory structure.
