### ISSUE TITLE
Force submissions to be public 

### ISSUE THREAD

**Issue by FlavioAlexander** [codalab/codalab-competitions#1589]
Currently, submissions are published by an organizer or the participant. A nice feature to have should be to force submissions to be public. Things to consider:
- Do we want one submission per participant? TBD
- Only finished submissions should be public.

Follow up to #1576

**Comment by vponcelo** [comment]
In my opinion for those competitions I manage, I think is better the first option, so that participants can decide which submission they want to download and test from other participants, as it is now. In case they are interested in the final submission (second option), they can filter them with the check box.
Best,
