### ISSUE TITLE
Submissions are stuck when participants upload them to CodaLab

### ISSUE THREAD

**Issue by spirinus** [codalab/codalab-competitions#1594]
Hi CodaLab,

we are running two CIKM Cup 2016 data science competitions on CodaLab right now: https://competitions.codalab.org/competitions/11171 and https://competitions.codalab.org/competitions/11161.

And, recently participants started to experience difficulties with getting their solutions scored. When they upload their submissions, the processing takes an excessively long amount of time (15min - 1hour). It limits the number of submissions that the participants can do per day and decreases their user experience on CodaLab (and transitively, satisfaction with the CIKM Cup). 

Can you please take a look at it and if possible increase the server capacity.

Thanks,
Nik (CIKM Cup 2016 Co-Chair)

**Comment by passick** [comment]
My submission is stuck for almost 24 hours now.

**Comment by dremovd** [comment]
I wanted to add, that this issue is not about speed of submission processing.

Submissions once in a "Submitted" status mostly never processed again. I have at least several this kind for days. More recent submissions are processed perfectly fine even if you submit same file 2 minutes after previous stuck submission. Affected submissions look random. 3-4 days ago I observed such behaviour first time and it happens now quite frequently (~10% submissions).

**Comment by madclam** [comment]
The datasciencegame was running this week-end, this may have cause the performance issue. Let us know if you are still experiencing the same problem.

**Comment by dremovd** [comment]
Unfortunately, there are same problems recurring.
As an example today: my submission 98 (login dremovd)

**Comment by Spirinus** [comment]
Hi @codalab Team, can you please investigate this issue. The participants repeatedly submit questions about this issue on the forum: https://competitions.codalab.org/forums/7911/1651/ and the unfortunate thing is that the problem is non-deterministic, i.e. for the same submission file it could fail (get stuck) or pass successfully.

**Comment by AtousaTorabi** [comment]
Hi,

We have the same issue for our competition, people are not able to submit their files.  for the same submission file it could fail (get stuck) or pass successfully.

Did you find any solution?

**Comment by dremovd** [comment]
No other solution but resubmit and hope for a better outcome. Currently in average more than half of submissions accepted. This situation is annoying but not blocking the work.

**Comment by Spirinus** [comment]
Thanks, @dremovd. No promises, but there is a chance that this problem will be resolved shortly. @FlavioAlexander is currently looking at it. Thanks, @FlavioAlexander!

**Comment by AtousaTorabi** [comment]
In mast few days over 80% of our submission get stuck in "submitted". It started really blocking the work in our challenge https://competitions.codalab.org/competitions/11531

Is there any quick solution to avoid this issue? 
Thanks!

**Comment by FlavioAlexander** [comment]
Duplicate #1598

**Comment by ssbilakeri** [comment]
i have submitted for dancetrack and got stuck in submitted. How to get the results
