### ISSUE TITLE
stuck in "submitting"

### ISSUE THREAD

**Issue by Shaoli-Huang** [codalab/codalab-competitions#1598]
stuck in competition of https://competitions.codalab.org/competitions/12061

any idea to fix?

**Comment by gautier-marti** [comment]
I am trying to set up a competition since yesterday. I encounter related submisision problems. I have also tried with the pi example to be sure that it is not a problem coming from my competition bundle.
Or, submissions go from submitting to submitted but with no results, and no lines in the leaderboard.

**Comment by indonoso** [comment]
I've been having the same problem since tuesday. These issues (#1594 #1595) talk about the same thing but there's no solution yet.

**Comment by arunmallya** [comment]
Same here. Would really appreciate an update.

**Comment by FlavioAlexander** [comment]
Some work was done on our side and things seem to be working as expected. I will keep this issue open for now. Let me know if anyone runs into this problem again
