### ISSUE TITLE
[urgent help] Cannot get verification email

### ISSUE THREAD

**Issue by sccds** [codalab/codalab-competitions#1604]
I am a student in UIUC CS410. One of my homework using CodaLab for a LeaderBoard competition.

After I register CodaLab, I cannot get the verification email. I have only one chance to register using my UIUC student name. So now I stopped at the signup step and can't continue to submit the homework. The homework will be due in about 12 hours.

My username is **xiaol2**
My email is **skywalkerxliu@aliyun.com**

Hope someone can help!

Thanks,

Xiao

**Comment by FlavioAlexander** [comment]
@sccds Sorry about your issue. Unfortunately, I did not see your issue on time. Did you ever receive the verification email?

**Comment by madclam** [comment]
We are sorry about that. The best solution in that case is to create another account (e.g. with another email). Otherwise, after a while the system times out and resends you a verification request. This gives you the opportunity to check your email address is correct. Also don't forget to check your spam.
