### ISSUE TITLE
Large file upload

### ISSUE THREAD

**Issue by relational** [codalab/codalab-competitions#1719]
Hello!

I am trying to upload a 435mb dataset, and I keep getting a 500 error without any feedback. Is there an issue with the platform? Our competition is using a validation dataset of size 429mb, which has been working fine.

Best regards,
Eirikur

**Comment by ckcollab** [comment]
On the test server or production? In the "My Datasets" section? Can you give me all of the details leading up to the error (including form values, like dataset type)?

**Comment by relational** [comment]
Thanks for the quick reply. This is on production, where my account name is "etagust", see screenshots. I created a smaller zip file using only 10% of the data, and then it uploads without error. I get the same error however when using 50% of the data (~220mb).

![files](https://cloud.githubusercontent.com/assets/3214177/24878950/69b66674-1e35-11e7-9b52-d80ef8b49ce6.png)
![form](https://cloud.githubusercontent.com/assets/3214177/24878955/6d7f3876-1e35-11e7-80a9-83c40ab764f4.png)
![result](https://cloud.githubusercontent.com/assets/3214177/24878963/72eecd12-1e35-11e7-9401-e21e4ca63d6b.png)

**Comment by relational** [comment]
UPDATE: I tried uploading the same zip file to the test server, and there the upload completes successfully.

**Comment by relational** [comment]
@ckcollab We are running [a challenge with >100 participants](https://competitions.codalab.org/competitions/16303), and the test phase is scheduled to end at April 16th. This issue is blocking us from uploading the test dataset of the challenge.
If someone could look at this before then, it would be highly appreciated!

**Comment by ckcollab** [comment]
@relational trying my hardest to get this working, we're in the middle of transitioning between large changes in Codalab so swapping back to the old style of things (which production is running on) makes it take extra long -- we're trying to figure this out though!

We have it narrowed down, we believe, to a problem with Azure uploads timing out... which is strange because this should have been working fine... trying to figure out what may have changed. 

In the mean time, is it possible you could create a new competition not using datasets, instead using a new competition bundle with the proper data? This will be a good Plan B if for some reason we can't get this working (I'll be up late tonight trying to fix if we can't fix it sooner). I assume you may run into the same upload timeout problem, though, when creating the new competition, so we'll just have to cross our fingers...

**Comment by ckcollab** [comment]
It looks like things are more broken than I was expecting, I'll keep trying to find a solution. The fix may requiring upgrading a dependency from a legacy version > 2 years old, but it doesn't seem to be working... will keep you in the loop...

**Comment by madclam** [comment]
We need to fix large file upload on LRI server.

**Comment by ckcollab** [comment]
This should be fixed on LRI server, I was able to upload `digits` dataset last time I tried, ~100MB if I recall correctly.

**Comment by ckcollab** [comment]
Tested again on LRI with > 100MB file
