### ISSUE TITLE
Changes in leaderboard from the editor

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1739]
We noticed that changes in the leaderboard made from the editor do not always take effect. This concerns for example the column keys.
In competition https://competitions.codalab.org/competitions/15525?secret_key=b59439f6-1f03-4f5b-8cb8-0d4044813cdc
for example, the column "precision"
The key and label were changed to bac_multiclass but the column is still called "precision" and Codalab still expects the scoring program to return something called "precision".

**Comment by jdchoi77** [comment]
Has this been resolved?  I'm one of the organizers for the SemEval 2018 shared tasks and it seems like the leaderboard label cannot be renamed no matter what changes we make in the editor.  Please take a look at this feature.  Thanks.

**Comment by ckcollab** [comment]
@jdchoi77 are you sure the form is actually saving? Sometimes the problem is that there was an error saving the form but the error is hard to spot. Does the competition edit form redirect back to the competition detail page when you hit submit?

**Comment by jdchoi77** [comment]
@ckcollab Yes, any other change I make in the edit form gets applied to the competition page except for this. Here is what I did:

1. Added a new scoring program that would print out "f1-score:%d" instead of "accuracy:%d" to `scores.txt`.
1. Updated the current phase with the new scoring program.
1. Updated the key and the label in the edit form of the leaderboard from "accuracy" to "f1-score".
1. Hit the submit button at the bottom.

When I submit a new output, it successfully runs but the score does not show in the leaderboard since it doesn't have the "f1-score" column but only the "accuracy" column.  Please let me know if this is not clear.  Thanks.

**Comment by madclam** [comment]
Has this been resolved?
