### ISSUE TITLE
Worksheets test

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1780]
Try to make an example Worksheets competition, work closely with Stephen Koo -- inform Xavier that we are doing this and get his advice throughout the process

**Comment by ckcollab** [comment]
Basically done with this, met with Stephen and discussed strategies/how we would go about things. Integrating things would be great, but I think a loose integration is all we can do for now, because users/authentication are so different. If we had a centralized user/auth then we could more easily integrate the two.

For example, submitting to a competition from a worksheet could be accomplished with a Codalab Competition's API key/secret of some sort in your worksheet. This has some problems (what if key leaks? typos? could be confusing to setup for some -- added barrier to entry?). What would be great for end users, I believe, would be an integrated experience where you sign up once and get access to all of the features which are integrated.

Also, Tyler is experimenting with worksheets to get a better understanding of their current state, to see what kind of integrations we can do.
