### ISSUE TITLE
broken submissions, internal server error on submissions page

### ISSUE THREAD

**Issue by gkata** [codalab/codalab-competitions#2013]
Hi all,

When I go to the submissions page of my competition (17422) I get the message 
Internal server error. Please file a bug report. For more information about CodaLab, check out the wiki.

I know this issue was reported before but I really hope to be able to find another solution then re-creating a new competition. I also have many broken submissions that have failed without any message. The previous phase of the competition worked well; when the new phase started I uploaded a new reference file without changing the leaderboard settings and the evaluation script and I got the error message "enter a valid slug...". I proceeded to change the leaderboard column names and the evaluation script so that they don't contain dots and the submissions have been failing ever since. The evaluation script works offline. 
I'd be grateful for any advice.
Kata

**Comment by ckcollab** [comment]
Could you give the user `eric2` administrative access to your competition? (Admins field when you edit the competition)

I can try taking a look, but this problem is a serious one and involves a lot of old old legacy code that is untested/fragile. We're currently rewriting Codalab to fix this problem once and for all... but it will be a while!

**Comment by gkata** [comment]
Thanks for your answer, I added you

**Comment by ckcollab** [comment]
One phase I am not able to access, but some I am... it does appear like this error isn't easy to fix though, hopefully we can handle this better in an upcoming release :(
