### ISSUE TITLE
top-three is not shown

### ISSUE THREAD

**Issue by hazirbas** [codalab/codalab-competitions#2142]
Hi,
Although there is one submission on the challenge (17807), the result is not show on the top-three. Is this normal?
Thanks,
Caner

**Comment by Tthomas63** [comment]
Hello Caner,

It looks like making submissions public is enabled. I think in order for the submission to show up on the top three it needs to be marked as `public` from the submit/view results tab, and the submission described is not. Please let us know if this does not fix it.

Thanks, and best regards,
Tyler

**Comment by hazirbas** [comment]
Hi Tyler,
I have tried it now and I still cannot see the score on top-three.
Caner

**Comment by Tthomas63** [comment]
Hello Caner,

I am not seeing anything that should cause this problem or errors reflecting a current issue. It does seem the leaderboard should show but is not for some peculiar reason I have yet to find. However creating a competition dump from your current competition and matching the settings from your current challenge, I can get the expected behavior from the leaderboard. 

Would you be able to try this and let us know? 

Best regards,
Tyler

**Comment by hazirbas** [comment]
I didnt get your point. I created dump and downloaded it. What shall do with it?

**Comment by Tthomas63** [comment]
Hello Caner,

Competition dumps are just competition bundles from the current state of your competition. It still has some settings missing, but will essentially be a copy of your current competition.

See [Wiki: Competition Dumps](https://github.com/codalab/codalab-competitions/wiki/User_Running-a-Competition#dumping-a-competition) for some more information.

Best regards,
Tyler

**Comment by hazirbas** [comment]
Thanks Tyler,
since I made the competition public and I have already registered users on the competition, I will not create a new competition from the dump file. For me, it is OK not to have top-three.
Thanks.

**Comment by Tthomas63** [comment]
HI Caner,

Okay. Please let us know if you have any more problems!

Best regards,
Tyler
