### ISSUE TITLE
Customizing the UI by only hosting the front-end server

### ISSUE THREAD

**Issue by tudorg-telenav** [codalab/codalab-competitions#2178]
Hi,

I've read under "Understanding the Codalab Architecture" that:

> Run an entire Codalab instance of their own with a preconfigured AMI or from scratch -- should not be necessary for most users, particularly because they can customize their front end WITHOUT running their own front-end server.

But I was not able to find any more information on that. Is this documented anywhere?

**Is it possible to have my own SPA as the only piece of architecture hosted on my side? And just use an API provided by the Django Web Backend (backend hosted on the Codelab side)?** I found no API reference to that, nor any documentation on that.

Thank you!

**Comment by ckcollab** [comment]
I think what that section was getting at was more about your competition pages (html included in competition bundles). 

You could probably talk to the API in some ways, but it's definitely not supported, so running your own SPA talking to competitions.codalab.org isn't really practical. If you wouldn't mind sharing more details about your use case I'd be interested to hear! We're working on Version 2 right now and I wonder what kind of features you'd like? Would you like to run the whole competition from your own domain (SPA), but use codalab compute resources? We want to have features like a widget that you could have on your Machine Learning class/seminar page for quickly making submissions to a competition, but I hadn't thought about completely running the competition offsite.

Do you imagine, for your use case, that you would still have a public competition? Would people only be able to access your competition via your SPA, or would they also be able to access it via the main codalab instance as well? I'd imagine you'd just want your SPA so the competition may be private... not sure we want to support this use case..

Again, would love to hear some more thoughts! I'm closing this though because we don't support it, yet.
