### ISSUE TITLE
Leaderboard is not shown

### ISSUE THREAD

**Issue by SimonOst** [codalab/codalab-competitions#2186]
Hi,
we are currently having a problem in our SemEval competition (https://competitions.codalab.org/competitions/17184). We are in the post-evaluation phase, and the leaderboard is not hidden in the phase settings, but it is still shown to neither participants nor organizers. What is also strange is that on the "Submissions" page, which we can access as organizers, the "RESULTS" column is missing in the list, while it is shown in other phases.

I think the phase was added later (although I'm not sure). Could this be the problem? And can we solve it somehow?

Thanks a lot in advance!

**Comment by ckcollab** [comment]
It *could* be because the phase was added later, that feature is rather finicky..

How many submissions should be appearing on the leaderboard? They are all "pushed to leaderboard?"

Thanks!

**Comment by SimonOst** [comment]
I just pushed one submission by one single participant to the leaderboard for testing (after resubmitting, btw). The participants uploaded more, but none of them is pushed to the board, as far as I can see.

**Comment by ckcollab** [comment]
When did this problem start happening? Was it working then stopped?

**Comment by SimonOst** [comment]
It's hard to tell, since I only realized this once the phase started - but I'm assuming that it has been there before.

**Comment by SimonOst** [comment]
Are there any news on the topic? Some participants already asked about this - otherwise, I'd try to find a workaround.

**Comment by ckcollab** [comment]
Could you add `eric2` as an admin for this? Will take a closer look

**Comment by SimonOst** [comment]
Sure. Thanks a lot!

**Comment by ckcollab** [comment]
Apologies for the delays on this... still trying to figure out what could be going wrong to display no leaderboard..

It *appears* somehow the leaderboard has become disassociated. Probably due to the phase not existing at the beginning of a competition. If I dump your competition, create it locally, make a submission, and send the submission to the leaderboard it works:
![image](https://user-images.githubusercontent.com/2185159/36693414-11ce0a44-1af0-11e8-8af3-47492528cccd.png)

So, painfully, you can re-create the competition and you will have a working leaderboard :(

We'll need to invest a lot of time to figure out what could be going wrong here, but we're so busy fixing bugs and working on V2 it's going to be hard to find time.

**Comment by j6mes** [comment]
Hi. Also running into this issue with adding new phase for our shared task. Still experimenting with the workarounds for this. Especially as we plan to introduce new phases with data we don't have yet part-way through the competition.
