### ISSUE TITLE
Leader board and table not shown

### ISSUE THREAD

**Issue by benbuleong** [codalab/codalab-competitions#2188]
Hi, I am running a competition and testing out the scoring program prior to the evaluation date.

https://competitions.codalab.org/competitions/17805#results

The phase used for testing -- called "sample testing" -- was created later after the original YAML file was submitted. For the visualizations, it seems that the leader board is not updated even though the "High score, Daily Total Submissions" statistics are displayed correctly. Also, I have looked at other competitions and there appears to be an excel-like "results" table displayed on the results tab as well, such as this: https://competitions.codalab.org/competitions/18113#results , whereas mine has no such results tab.

Is this a bug with the current public instance of CodaLab, or am I missing some settings?

**Comment by Tthomas63** [comment]
Hello @benbuleong,

It appears your leaderboard is dissasociated from the rest of your competition

**Comment by Tthomas63** [comment]
Hello @benbuleong 

It appears your leaderboard is disassociated from the rest of your competition. This likely happened while adding phases and adjusting your leaderboard after uploading, as this can be quite buggy due to the fact that these objects all reference each other after creation, and editing them can sometimes have unintended consequences like null references to keys that don't exist.

<img width="1428" alt="screen shot 2018-02-16 at 12 10 09 pm" src="https://user-images.githubusercontent.com/28552312/36327162-9b8ed60e-1312-11e8-87a8-4e3063b52948.png">

This can be seen from the YAML, as your leaderboards have completely different keys/labels to the original, and your phases switched from starting at index 1, to starting at index 0.

It is probably not possible to re-cover the current competition to working order. It would probably be best to download a competition `dump` ( A clone of the current state of your competition ), and attempting to use that to create a new competition. 

Sorry for any inconvenience, and best regards,

**Comment by benbuleong** [comment]
I see -- thanks for the debugging. If I create a dump and recreate the competition, will all the URLs change?

**Comment by lopuhin** [comment]
Hello @Tthomas63 , I think we have the same or very similar issue: I added a second phase to the competition via web UI after the end of the main phase (we decided to add an additional phase so that participants could check variations of their solutions). Here https://competitions.codalab.org/competitions/17810 I made one test submission in a second phase, but leaderboard is not shown for the second phase. Is there anything that can be done besides creating another competition (we don't want to remove the old one because it has official results)?

**Comment by Tthomas63** [comment]
Hello @lopuhin, and @benbuleong 

Yes the new competition will have a different URL. Your competition data/settings should remain the same, the only thing not carried over is user submissions/results unfortunately.

We have not found a solution for this specific bug/condition, or the exact cause. Currently the best solution we have found is using the "dumps" feature to create a competition zip from your current competition's state and re-uploading. 

A common cause of this issue seems to be creating/inserting new phases or changing the leaderboard in a similar fashion from the edit form. 

Thanks, and best regards,

**Comment by lopuhin** [comment]
Thank for looking into it @Tthomas63

**Comment by lopuhin** [comment]
@Tthomas63 just to confirm, there are no other ways to add a new phase to a competition besides by using an edit form, right?

**Comment by Tthomas63** [comment]
Hello @lopuhin,

Once the competition is uploaded, the edit form is the only way to edit that competition instance.

Unfortunately I think if a decision is made to add more phases or edit the leaderboard on a competition, the safest way to implement this would be to edit the original YAML and re-upload as a new competition.

Best regards,
Tyler
