### ISSUE TITLE
Cannot update any information through 'Edit' after uploading the bundle to CodaLab

### ISSUE THREAD

**Issue by SuperIRabbit** [codalab/codalab-competitions#2204]
Cannot update any information through 'Edit' after uploading the bundle to CodaLab

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
Since it's impossible to edit and save the information, I cannot add them to the competition now.
2. Please post a link to your competition
https://competitions.codalab.org/competitions/18229

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
- I tried both Chrome and Firefox
2. What is the URL of the problem? 
- https://competitions.codalab.org/competitions/edit_competition/18229

**Comment by SuperIRabbit** [comment]
After multiple trial-and-errors I found that if the yaml does not contain the 'reference_data:' field, the uploaded competition will be un-editable. Can anyone look into this problem?

**Comment by Tthomas63** [comment]
Hello @SuperIRabbit,

It seems it may actually be possible to fix the competition even with the weird behavior on edit page. 

1) Create a new dataset of type `reference_data` from the `My Datasets` section of Codalab
2) Go back to the competition edit form, and set the newly created `reference_data` to the reference data field for your phase. Click the `submit` button at the bottom to save.
3) Clicking `submit` should bring you back to the form, but now the reference data field should display an error ( Saying it is required )
4) Repeat step 2, but this time clicking the submit button should actually submit the form, and return you to the competition detail. If you view the edit page again, everything should be working.

In order to avoid this behavior with the edit form, we're adding a check to competition unpack for reference data. If while unpacking your competition it does not find any `reference_data` for a phase, it will throw an exception and halt. (See PR: #2217)

Please let us know if you have any further problems.

Thanks, and best regards,
Tyler
