### ISSUE TITLE
Codalab local instance Failed to upload competition bundle

### ISSUE THREAD

**Issue by MorganTHobson** [codalab/codalab-competitions#2394]
We would like to set up a local instance of codalab competitions on our own server, however, once the server and S3 storage have been set up, we are unable to upload competition bundles to the server. On upload attempts, the following message is returned: [https://i.imgur.com/oEO8Jmp.png](https://i.imgur.com/oEO8Jmp.png)
This was after following the instructions on the following pages:
[https://github.com/codalab/codalab-competitions/wiki/Setup-Local-Competitions#user-content-get-the-source-code](https://github.com/codalab/codalab-competitions/wiki/Setup-Local-Competitions#user-content-get-the-source-code)
[https://github.com/codalab/codalab-competitions/wiki/Storage](https://github.com/codalab/codalab-competitions/wiki/Storage)

**Comment by ckcollab** [comment]
I am not sure, it is actually rather difficult to debug these problems. It is probably a problem with your bucket policies, though.

I'm closing this issue as it's not a problem with Codalab or the production platform, but probably with your configurations. I will keep answering questions here though, if I miss something feel free to email me eric@ckcollab.com for more help!

**Comment by viaudg** [comment]
Hi,

We have the same problem here by using Minio. We are trying to install our own version of `codalab-competitions` on local servers to perform some tests using our own HPC environment. We have successfully followed the instructions on 
[this page](https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers). We then wanted to set up our data storage using Minio, so we followed [this guide](https://github.com/codalab/codalab-competitions/wiki/Minio-storage).

We then tried to upload a competition bundle on the website. We know that the competition bundle is correctly uploaded when using the official [https://competitions.codalab.org/](https://competitions.codalab.org/) website. However, on our local codalab, we always have an error of the type `"Sorry, failed to upload file."`. We have correctly filled in the `AWS_S3_HOST` field (we have actually tried many different things just in case). We also have set the policies to allow for `"read/write"`everywhere just in case. We have seen nothing relevant in the logs of `/var/logs/django/`.

@MorganTHobson Did you solve your problem?

@ckcollab Are there any other log files that we can check or things that we can try in order to better diagnose the problem? Do you have any idea where this comes from?

Many thanks to both of you,

**Comment by asm582** [comment]
@viaudg did you manage to solve the above issue?
