### ISSUE TITLE
Send task to SLURM

### ISSUE THREAD

**Issue by DWL3** [codalab/codalab-competitions#2439]

**Comment by ckcollab** [comment]
I have been added to this now.

# Thoughts:


#### Structure vs normal compute worker

A normal compute worker sits and waits for Celery to send it a job then it executes the job. This will be basically the same thing, except the actual running of the job will be done through `sbatch`. So, instead of `docker run` we'll write the docker run command to some `run.sh` file, and then execute this script inside `sbatch`.

Does `sbatch` run in some kind of isolated environment? I remember reading that some directories on this Titanic server stuff shouldn't be messed with.

#### Send to ONLY the same type of GPU, otherwise could get mixed results

```bash
$ sbatch --gres=gpu:2 -C pascal script.sh
```

#### How do we handle timeouts..?

The script could hang forever waiting for a GPU.
