### ISSUE TITLE
Results (low to high)

### ISSUE THREAD

**Issue by GregorySlabaugh** [codalab/codalab-competitions#2462]
Hello, 

We're currently running a competition: https://competitions.codalab.org/competitions/20179 

In our competition, a good scoring result has a high positive value (as we are measuring a peak signal to noise ratio, or PSNR).  

On our Results page, the Leaderboard is functioning correctly, with the best scoring submission in position 1 at the top of the Leaderboard.  However, the chart (red plot) is showing the _lowest_ scoring submission for each day.  

How can we reconfigure the red plot to show the _highest_ scoring submission for each day, while keeping the Leaderboard showing the highest score in the first position?

I've tried changing the Leaderboard from Descending to Ascending (Edit->Leaderboard->PSNR->Sorting) but this doesn't work as it puts the highest scoring submission in the last position, and flips the plot upside down.

Many thanks for any help!

**Comment by madclam** [comment]
Hi Gregory,

This looks like a bug and I don't know how to do that. Eric and Tyler as swamped. My suggestion is that you turn off the little chart by clicking "Hide Chart" in the editor.

You may want to fix the bug yourself since the code of Codalab is open-source and submit a pull request.

Isabelle
