### ISSUE TITLE
[-] button disappears

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2560]
This concerns competition:
https://autodl.lri.fr/competitions/115

When expanding with [+] button in entry 2371 (which has a large error message), the [-] button disappears.

<img width="636" alt="Screen Shot 2019-04-11 at 9 48 06 AM" src="https://user-images.githubusercontent.com/7594063/55939831-0e0def00-5c3f-11e9-98d6-6634b3040ae7.png">

**Comment by Tthomas63** [comment]
I believe this was due to the traceback overflowing (A related issue).

This should be solved now with better formatting/alignment on the traceback. Please let me know if there are still issues with the formatting of the table/traceback.

![screencapture-localhost-competitions-1-2019-04-12-16_19_53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594802f30ac590001a3ca1a3/125516c66e82c728ace21e0d46fb978826878daa8ef9ab56b658bd982645267f210bb03f3d86ec25af476f081b0611f202455e59fef98822bbb6386d8b5e16ecd7025e7da93812bea4905ffd5ee075d80b97bcae8f1e93ef3b76e08e8e1c374b531c89ff5534f59d4bca5df459fd5f17f54d623cbb2f7c29058614672d6d6d27aef9da57868466a7b218285fdaae.png)
