### ISSUE TITLE
Supporting Python3

### ISSUE THREAD

**Issue by siabar** [codalab/codalab-competitions#2584]
Can I write scoring_program in python3?

It seems it is not possible. I got this error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"python3\": executable file not found in $PATH": unknown.

**Comment by ckcollab** [comment]
Is it not using Python 3 already? You can modify/change the Dockers it is running on?

**Comment by siabar** [comment]
Sorry, can you say how can I do it? 
in scoring_program I just changed  metadata from python evaluate.py .... to python3 evalaute.py I got this error. how can i change it to adapt to python3?

**Comment by ckcollab** [comment]
Change the docker image the competition is using (via competition edit form). Also, there should be information about changing dockers in the Wiki somewhere, if not let me know and I'll try to add a section for it.

**Comment by siabar** [comment]
Hi Eric, I changed the Competition docker image to codalab/codalab-legacy:py3.
After that, I submitted a submission. I did not get any error but also it does not show any results. what is wrong?

**Comment by siabar** [comment]
It solved. My code had an error

**Comment by apiad** [comment]
I'm having this same problem, I need Python 3. Tried changing the docker image to `codalab/codalab-legacy:py3` and using either `python` or `python3` in the metadata. In the first case it fails to import `pathlib` so I assume is using `python2`. In the second case it says `\"python3\" not found in $PATH`.

I also downloaded the codalab legacy image, installed Python 3 and uploaded to Docker Hub (`apiad/codalab:python3.4`), and with that image it has the same error, even though I check that I can run `python3` inside my custom docker image.

Is it possible that Codalab is somehow not honouring the custom docker image option?
Or could I have a problem in my metadata file:

```
command: python3 $program/eval.py $input $output
description: Evaluation script
```

**Comment by apiad** [comment]
I solved my problem! I'm leaving the details here for reference.
I actually had two different issues (both my own fault):

1. When you change the docker image you **cannot** re-run a submission, but have to resubmit from scratch. I found out this by reading other issues, but I think it would be nice to add it to the Wiki documentation on using your own docker image.
2. After fixing that, my `eval.py` file was writing to a `score.txt` **instead of** `scores.txt`. I know, totally my fault. It would be nice, however, if Codalab could at least signal an error, in this case, saying "No scores.txt file output, please check the filename" or something like that, because I spent well over two hours just on this tiny mistake.

Anyways, I'm glad I solved, and by the way, to all the Codalab team, thanks for developing this great product :)
