### ISSUE TITLE
404 Could not find the page you requested. https://competitions.codalab.org/competitions/20429

### ISSUE THREAD

**Issue by onexxp** [codalab/codalab-competitions#2646]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by Didayolo** [comment]
If you are not the competitions organizer, the competition could have been deleted. But if you are the organizer and didn't delete it, it is more likely due to the crash of the platform.

Following a major crash of our system, we restored Codalab from an older backup. Some competitions and some user accounts could not be restored.

We sincerely apologize for the inconvenience. We have put in place better backup and recovery procedures so this problem will not recur.
