### ISSUE TITLE
Error while parsing the data_7000.csv of the Memotion Analysis Challenge

### ISSUE THREAD

**Issue by aryan9600** [codalab/codalab-competitions#2696]
I get an error when I try to parse through the data_7000.csv. 

`df = pd.read_csv('data_7000.csv')`

`ParserError: Error tokenizing data. C error: Expected 9 fields in line 671, saw 17 site:stackoverflow.com`

**Comment by Didayolo** [comment]
Hi,

I think this issue comes from the data itself, therefore you should contact the challenge organizers.

This repository is dedicated to the platform itself (Codalab).

By the way, this type of error during parsing a CSV file usually occurs when the separator are present in the data. 
For example:
```
1 x,y,z,date
2 0,6,2,02/17
3 1,2,1,02/21
4 3,4,0,03,05
5 9,0,2,03/12
```

In this example, an error while occur in line 4.
