### ISSUE TITLE
Competition page empty for non-logged-in users

### ISSUE THREAD

**Issue by leondz** [codalab/codalab-competitions#2771]
Hi,

Competition 22998, https://competitions.codalab.org/competitions/22998, doesn't load when I'm not logged in as admin. I'm using Firefox 75.0 and Chrome 81 / Ubuntu 18.04. Both give a white page / 404 for this competition when not logged in. This makes it tough for people to discover the competition, get the data, ... see a login form.. . Any idea how to improve things?

**Comment by Didayolo** [comment]
Hi,

Thank you for your patience. The competition is showed only when you are logged as admin because **it is private**. 

You can:
* Make it public through the "EDIT" menu or with the "publish" button in "my competitions".
* Keep it private but then to be able to access it, people will need the secret URL that you can find on top of your competition.

**Comment by leondz** [comment]
Well, that doesn't seem like a bug at all! Thank you.
