### ISSUE TITLE
Submissions stuck in "submitted" 

### ISSUE THREAD

**Issue by carolscarton** [codalab/codalab-competitions#2808]
Hi, it is my first time organising a competition with CODALAB and we are having issues with the submissions page. 

Yesterday, my colleague and I managed to make submissions without any issue and we can see them there. Today, when we went to try again, the submissions just stay with the status "submitted" forever. Is there an issue with your servers that may be causing it? 

Also, when I open the file "View scoring error log" for the submission tagged as "submitted, I can see the following message "Standard error for submission #0 by <user>". For submissions tagged as "finished" the error log has a warning. 

We appreciate all the help!

**Comment by Didayolo** [comment]
Hi,

I think the submissions stuck in "submitted" state can be caused by many things.

Can you please provide more information about your competition? Did you change the "worker queue" in the EDIT menu?

If you want, you can add me as an admin of the competition so I can have a look. My Codalab's ID is "pavao".

> Also, when I open the file "View scoring error log" for the submission tagged as "submitted, I can see the following message "Standard error for submission #0 by ". For submissions tagged as "finished" the error log has a warning.

Your logs seems normal to me.

**Comment by belerico** [comment]
HI,
same issue for me: I'm partecipating to the "SemEval 2020 Task 1: Unsupervised Lexical Semantic Change Detection" (https://competitions.codalab.org/competitions/20948), but I'm stuck at "Submitted".
The scoring output and the scoring error display blank pages with "Standard error for submission #6 by belerico." at the beggining.
Thank you for the help!

**Comment by Didayolo** [comment]
Hi Belerico,

As a participant, you should directly contact the challenge organizers as the issue is probably on their side (or on yours if you submission has a problem). This is the platform's Github repository and it is quite independent from challenge organizers.

Thank you for your understanding.

**Comment by carolscarton** [comment]
@Didayolo, thanks for your reply. I think it was a server issue. It started work after that and has been working fine since :)
