### ISSUE TITLE
submission failed but result exists and is posted in table

### ISSUE THREAD

**Issue by mgerdzhev** [codalab/codalab-competitions#2839]
am participating in one of the competitions: https://competitions.codalab.org/competitions/20331
User MG
When I uploaded a submission, the status said Failed, but results were computed and posted to the leaderboard. Because it was a Failed attempt, I cannot remove it from the leaderboard. Can that somehow be fixed?

**Comment by Didayolo** [comment]
Hi,

It seems strange to me that the submission is visible on the leaderboard after having failed.

Maybe it's due to some configurations of the competition (e.g. the `force submission to leaderboard` option).

If you really want to remove your submission, you can contact the admins (organizers) of the competition and ask them to delete your failed submissions.

**Comment by mgerdzhev** [comment]
Thanks they removed it from the leaderboard but it was strange
