### ISSUE TITLE
Execution time limit exceeded!

### ISSUE THREAD

**Issue by PemasiriAkila** [codalab/codalab-competitions#2864]
During a submission on FreiHAND competition, the submission status came as failed (with the error log "Execution time limit exceeded!"). 

To double-check the correctness of the submission, I downloaded a zip folder which was successfully submitted previously and the same error was coming up.

Any suggestions

**Comment by Didayolo** [comment]
Hi,

This is likely due to the submission itself or to the FreiHAND competition.

I suggest that you try to contact FreiHAND competition organizers directly.

This repository concerns the platform Codalab itself and the bugs related to it, not to specific competitions. For instance, if the organizers have lowered the execution limit, only them can correct this issue.

**Comment by shreyashampali** [comment]
Hi,
I organize HO3D competition (https://competitions.codalab.org/competitions/22485) and submissions to this competition are also facing the same issue. Basically, submissions take a lot of time (3-4 hrs) to start running and once it starts it exits due to execution time limit. I increased the execution time limit to 2000 and from 1000 and issue still persists. Could you please help?

**Comment by PemasiriAkila** [comment]
@Didayolo I checked with FreiHAND competition organizers, and it appears that they have not made any changes.

**Comment by Didayolo** [comment]
I think this was due to issue with new compute workers and is solved now.

Please re-open the issue if you're still facing the bug.
