### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by WebDevelopmentLabs** [codalab/codalab-competitions#2873]
1. I am using Chrome 80.03987
2. https://competitions.codalab.org/7462 - this and all the pages listed here: https://competitions.codalab.org/competitions/2321 say "Page Not Found"

**Comment by Didayolo** [comment]
Hi,

Thank you for reporting. Those pages are indeed unreachable.

This might be due to the crash we faced last year - some competitions couldn't be retrieved. But this shouldn't affect old competitions like this one. I don't really know what's going on.

By the way, you may be interested in the [AutoDL challenge series](https://autodl.chalearn.org/) which is the most recent versions of AutoML challenges.

**Comment by WebDevelopmentLabs** [comment]
Dear team,

Thank you so much for the kind response, really appreciate it. I am
actually a beginner in Machine Learning domain, thus, was looking for some
information in the pages of AutoML there. I will look in to the AutoDL by
the way, it seems helpful for my next lessons :-)

Thanks J
Malik


Best Regards,
Malik
*Co-Founder/Customer Success Head*


*Skype:* webdevelopmentlabs / najib.malik
*E-mail: *info@webdevelopmentlabs.com
*Website: *www.webdevelopmentlabs.com

CONFIDENTIALITY NOTICE: The contents of this email message and any
attachments are intended solely for the addressee(s) and may contain
confidential and/or privileged information and may be legally protected
from disclosure. If you are not the intended recipient of this message or
their agent, or if this message has been addressed to you in error, please
immediately alert the sender by reply email and then delete this message
and any attachments. If you are not the intended recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message
or its attachments is strictly prohibited.
