### ISSUE TITLE
Not showing Leaderboard

### ISSUE THREAD

**Issue by svc2021bida** [codalab/codalab-competitions#2930]
Hello,
I'm trying to start a phase of the competition but when it comes to display the results in the table, it doesn't show them.
The submissions are uploaded correctly but they are not shown in the tables.

My competition is: https://competitions.codalab.org/competitions/27802

I would appreciate if you could help me.

Attached to this message are a screenshots of my CodaLab configuration.

![Captura](https://user-images.githubusercontent.com/82283352/114279432-f5ef2700-9a34-11eb-92a6-6eaaacaf1df4.PNG)
![Captura](https://user-images.githubusercontent.com/82283352/114279471-259e2f00-9a35-11eb-9558-512ce22bbd88.PNG)

**Comment by Didayolo** [comment]
Hi,

Sorry for the late reply. 

It could be something due to the name of the score produced in the `scores.txt` file which has to be the same as in the EDIT menu / YAML file.

If you still need help with this, you can add me as an admin of the competition so I can have a look.
My Codalab ID is `pavao`
