### ISSUE TITLE
updating the yaml file

### ISSUE THREAD

**Issue by shreyashampali** [codalab/codalab-competitions#2965]
Hi,
I am currently organizing a challenge (https://competitions.codalab.org/competitions/33267) in which I need to update the leaderboard with one more metric for evaluation. As I can see from other posts here, this is not possible from the 'edit' option in the browser and I need to update the competition bundle with new yaml file.  Could you please help me with the following?
1) How do I update the yaml file? I do not see an option to reupload the bundle once the competition is created.
2) After reuploading the bundle will the existing leaderboard remain intact ? i.e., will the results of the participants before updating the bundle can be still seen after the update?

thanks!

**Comment by loicsarrazin** [comment]
Hi @shreyashampali 

It is not possible right now to add a column in the competition editor. Reuploading the yaml file should not be necessary since this kind of modification to a competition should be made via the editor. To re-upload a yaml file, you need to create a new competition. It is not possible to transfer the results, leaderboard and participants from one competition to another. 

I hope this answers your question.
