### ISSUE TITLE
get stuck in submitted status 

### ISSUE THREAD

**Issue by lxa9867** [codalab/codalab-competitions#3007]
did codalab break down again?

**Comment by dalision** [comment]
Hi codalab maintainers and everyone, I prepare to organize [misp2021](https://mispchallenge.github.io/index.html) competition on codalab, here is a test version of the [competition](https://competitions.codalab.org/competitions/36322). But it seems that I get stuck in submitted status as you mentioned 23 days again, is there anything getting better, do you still have the same problem?

**Comment by KaiHe-better** [comment]
Hi,


Codalab&nbsp;was back to normal after one day the problem occured.&nbsp;


I can use it normally yesterday.


------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "codalab/codalab-competitions"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Nov 17, 2021 03:31 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [codalab/codalab-competitions] get stuck in submitted status  (Issue #3007)





 
Hi codalab maintainers and everyone, I prepare to organize misp2021 competition on codalab, here is a test version of the competition. But it seems that I get stuck in submitted status as you mentioned 23 days again, is there anything getting better, do you still have the same problem?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Didayolo** [comment]
Hi,

I guess we need to attach more compute workers to the new server, as the activity is increasing rapidly.
