### ISSUE TITLE
[LISN / Python3] Error when saving edits

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#3018]
When saving edits, we get the following error message:

```
The CodaLab site is currently unavailable.

Sorry, the page you are looking for is currently unavailable.

Please try again later.
```

However, **the changes are effectively saved**. So it's maybe just a problem of redirection.

**Comment by loicsarrazin** [comment]
After quickly analyzing the behavior locally, it would seem that the save edits fails because of empty "phase number" fields (at least on my side).   
  
For example, adding values to the phase number fields that are empty (I think there are 2 by default, at least when using sample competitions)  
  
This should help down pinpoint the issue. I was able to reproduce the bug locally, but @Didayolo was not. We were under the impression that @Tthomas63 you had fixed this at a certain point in the last few months.

**Comment by Didayolo** [comment]
Working on it.

**Comment by Didayolo** [comment]
Solved.
