### ISSUE TITLE
hello! if the old Codalab is phased out,Will the lits(liver tumor segmentation challenge) migrate to the new website？

### ISSUE THREAD

**Issue by luoshiyong** [codalab/codalab-competitions#3044]
hello! if the old Codalab is phased out,Will the lits(liver tumor segmentation challenge) migrate to the new website？

**Comment by talhaanwarch** [comment]
I wish they automatically migrate all competitions

**Comment by Didayolo** [comment]
Currently the competitions need to be re-uploaded to appear in the new server. However, even if at some point it will not be possible to create new competitions in the old server, the already existing competitions will remain accessible.

We plan to upgrade the old server at some point, or to attach the old server's storage to the new server in order to keep all competitions accessible in a good shape, if possible... However that might be a tricky operation, so it is hard to promise it right now.

Thank you for your comprehension.
