### ISSUE TITLE
Status stuck on "Submitting"

### ISSUE THREAD

**Issue by Jaehyun0818** [codalab/codalab-competitions#3048]
Hello, I'm a participant of "SemanticKitti: Semantic segmentation".
I submitted the test result four times in codalab website, however the status of those submissions are stuck on "Submitting" for 2 days.
Furthermore, three of them are removed on result table and only one of the result is remained like the figure.
Is there any idea about the issue??
Thank you!
![image](https://user-images.githubusercontent.com/47267562/144015435-59b20cf8-c89f-4c8d-a3bd-c58a0e06ac73.PNG)

**Comment by Didayolo** [comment]
Hello,

This issue is a clone of #3045, so I'll close it.

The submissions are stuck on submitting because of the huge activity on the platform. Please avoid to re-upload many times your submission.

> Furthermore, three of them are removed on result table and only one of the result is remained like the figure. Is there any idea about the issue??

Maybe the challenge organizers unable the option to "delete all submissions except the last or best".
