### ISSUE TITLE
SEND VERIFICATION MAIL FOR SIGN UP 

### ISSUE THREAD

**Issue by Keeri18** [codalab/codalab-competitions#3083]
keerthana.madhavan2019@vitstudent.ac.in no the verification mail isn't in my spam folder

**Comment by Keeri18** [comment]
Still haven't received a verification mail

**Comment by Didayolo** [comment]
Hi,

I paste your other issue here in order to clean up:

> https://competitions.codalab.org/accounts/login/ via google chrome is not sending keerthana.madhavan2019@vitstudent.ac.in a verification mail for sign up/sign in

I just try signing up and it worker. Please double check you didn't received it, and check with your email provider (it is a University mailbox?).

By the way, CodaLab is now mainly located in this new server: [codalab.lisn.fr](https://codalab.lisn.fr/). In the case you don't have a specific reason to sign up to this old server, it is preferable to sign up into the new one.

**Comment by Didayolo** [comment]
Did you try with a personal email? University mailing services often have strong filters. On our side, the mailing bot seems to be working well.

**Comment by Keeri18** [comment]
Yes, it worked.

**Comment by Didayolo** [comment]
I'm glad that you could solve your problem.

_Note for the future: I've found a way to accept email address "by hand" and have reported it in the [Admin Wiki](https://github.com/codalab/codalab-competitions/wiki/Dev_Administrator-Procedures)_
