### ISSUE TITLE
Please enable submit on old website or transfer old competitions to new website

### ISSUE THREAD

**Issue by leaf1170124460** [codalab/codalab-competitions#3221]
I want to evaluate on youtube vis 2021 (https://competitions.codalab.org/competitions/28988) , but it is not allowed to submit results on the old website. Moreover, this competition is not available on the new website. If the old website is not available in the future, please transfer old competitions to the new website to provide us a way to evaluate results. Suddenly closing the result submission entrance is not a friendly way.

**Comment by dtuantran** [comment]
Dear @leaf1170124460 ,
Since several months ago, we did inform the community on the Home page of old website and on the Google Group about phasing out this website. In order to migration a competition, you can find more information here : https://groups.google.com/g/codalab-competitions/c/xJlHTZAgztM
Thank you for your understanding.
Regards,
Codalab team

**Comment by Didayolo** [comment]
Transferring a competition to the new website is quick and easy for the organizers. It is just needed to dump the bundle and re-upload it (see here https://github.com/codalab/codalab-competitions/wiki/User_Running-a-Competition).

We let the organizers decide whether they want to update their competition to the new server.
