### ISSUE TITLE
Submit for blind test issue

### ISSUE THREAD

**Issue by qianrenmao** [codalab/codalab-competitions#3255]
***submit for blind test issue***

Fact Extraction and VERification (FEVER) Challenge
-----------------------------------

It seems like there is a bug in the code of the online test, causing we failed to submit predictions. 

We have strictly checked the submission format referring to the Answer Submission Instructions 

File "/tmp/codalab/tmpB3pmfs/run/program/evaluate.py", line 18
    print "%s doesn't exist" % submit_dir
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s doesn't exist" % submit_dir)?

Waiting for the reply urgently. THX

**Comment by Didayolo** [comment]
Hello,

I think it is not due to the version of the server, but to the recently updated version of the default docker image used to evaluate submissions (see https://groups.google.com/g/codalab-competitions/c/byvq0n7Vc2k).

 If no competition docker image is set in a competition, then the default image is used so this change can have an effect.

The new default image is `codalab/codalab-legacy:py39`.

I have to check but I think the old one is `codalab/codalab-legacy:1.0.1`. So, setting `codalab/codalab-legacy:1.0.1` as the competition docker image should solve the problem. 

**Please give me the URL to the competition and I'll make this change.**

**Comment by Didayolo** [comment]
Let's treat this problem in the following issue: https://github.com/codalab/codalab-competitions/issues/3263
