### ISSUE TITLE
FEVER Competition seems to be running wrong Python version on server

### ISSUE THREAD

**Issue by mitchelldehaven** [codalab/codalab-competitions#3261]
This seems like the same problem in #3255 . I tried both with a new input and input that was known to work prior to the competition migrating to the new site and get the following error message on both.

```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  File "/tmp/codalab/tmp4RAvfx/run/program/evaluate.py", line 18
    print "%s doesn't exist" % submit_dir
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s doesn't exist" % submit_dir)?
```

There appear to be two submissions since migration to the new website, so I'm not sure if something changed between now and then.

**Comment by Didayolo** [comment]
Hello,

I think it is not due to the version of the server, but to the recently updated version of the default docker image used to evaluate submissions (see https://groups.google.com/g/codalab-competitions/c/byvq0n7Vc2k).

 If no competition docker image is set in a competition, then the default image is used so this change can have an effect.

The new default image is `codalab/codalab-legacy:py39`.

I have to check but I think the old one is `codalab/codalab-legacy:1.0.1`. So, setting `codalab/codalab-legacy:1.0.1` as the competition docker image should solve the problem. 

**Please give me the URL to the competition and I'll make this change.**
