### ISSUE TITLE
Cannot evaluate results on The 4th Large-scale Video Object Segmentation - Track 3: RVOS (migrated server)

### ISSUE THREAD

**Issue by VegetableChlcken** [codalab/codalab-competitions#3262]
Hi,

I tried to evaluate the results as usual on https://codalab.lisn.upsaclay.fr/competitions/6066. But there is something wrong with the evaluation system. Maybe it is caused by the possible python version update of your server? I've checked that the server has scored all my submitted answers in the stdout but just failed to write down the summing-up score. The error information is like:

Traceback (most recent call last):
  File "/tmp/codalab/tmpvJpfeJ/run/program/evaluate.py", line 240, in <module>
    output_file.write('Overall: {}\n'.format(overall))
TypeError: a bytes-like object is required, not 'str'

Thanks.

**Comment by Didayolo** [comment]
Same as #3260.

Hello,

I think it is not due to the version of the server, but to the recently updated version of the default docker image used to evaluate submissions (see https://groups.google.com/g/codalab-competitions/c/byvq0n7Vc2k).

If no competition docker image is set in a competition, then the default image is used so this change can have an effect.

The new default image is `codalab/codalab-legacy:py39`.

I have to check but I think the old one is `codalab/codalab-legacy:1.0.1`. So, setting `codalab/codalab-legacy:1.0.1` as the competition docker image should solve the problem.

**I have made the change, please tell me if it is now working.**

**Comment by Didayolo** [comment]
Let's treat this problem in the following issue: #3263
