### ISSUE TITLE
Large Submission File Size Causes Slow, Buggy Performance

### ISSUE THREAD

**Issue by blahner** [codalab/codalab-competitions#3296]
We are testing a "sandbox" version of our Codalab competition before publishing it, and we notice some issues with Codalab loading large submission file sizes. Our submission file sizes are roughly ~290MB, pushing against Codalab's upper limit of 300MB. Upon submitting such a large file, Codalab seems to take on the order of minutes to complete the upload or it simply does not upload (and Codalab does not provide a submission progress bar or any other feedback to the participant, making the problem difficult to diagnose). Unfortunately, I cannot reproduce this issue - using the same submission file, sometimes the upload is fairly smooth (~10-15 second upload time) and the scripts run fine, and other times I can't seem to upload the submission even after numerous attempts and versions of the competition. 

When I use a subset of the same submitted data (so much smaller file size, ~25MB), I do not have any issues. This makes me think Codalab has trouble uploading large file sizes.

Do you know of this issue and any possible solutions? Is there any way to give the participant feedback on their submission upload (e.g. a progress bar)? I appreciate your help!

**Comment by Didayolo** [comment]
Hi,

The symptoms you describe seems to be related with the quality of the internet connection. In the past we had competitions with huge submissions and I think it worked well. Maybe we need to do some testing, or maybe your connection quality is variable.

Just to confirm: are you using the public instance of CodaLab or did you deploy your own instead of the platform?

As you mention, the main issue is the lack of progress bar during the upload (#1920 #3022). This simple GUI fix could make it way clearer.

**Comment by blahner** [comment]
Hi,
Thanks for the response! I am using a public instance of CodaLab, processing result submissions on your provided machines. At first glance it looks like the progress bar feature was merged 1-2 months ago, is there something else I need to do to get that progress bar feature on my competition? That would definitely be helpful. Thanks!

**Comment by Didayolo** [comment]
Unfortunately this simple feature was never implemented and merged.

Just the issue was merge into this bigger one #1920

If you wish you can contribute to the project by implementing the progress bar and making a pull request.
