### ISSUE TITLE
Visual Domain Decathlon Challenge Not Available

### ISSUE THREAD

**Issue by askliar** [codalab/codalab-competitions#3322]
I would like to use Visual Domain Decathlon dataset. Since it was hosted on an old version of Codalab, it's not possible to get any results anymore.

This is the link to competition: `https://competitions.codalab.org/competitions/17001`.
Is there any way to move it to a new version as well?

**Comment by Didayolo** [comment]
Hello,

We let the organizers transfer their competition by themselves. It is a simple procedure (dump + reupload).

Please contact the organizers to ask them to transfer their competition to codalab.lisn.fr

Thank you for your comprehension.

**Comment by carandraug** [comment]
Hi @Didayolo. We would like to migrate the competition but we would also like to transfer the leaderboard. Can this be done? (cross posting from https://groups.google.com/g/codalab-competitions/c/b-oBpeMS8j0 since it appears that google groups is abandoned)

**Comment by Didayolo** [comment]
Hi @carandraug,

I don't know anyway of transfering the leaderboard, as the user accounts of the original competition's participants may not be existing anymore.

**Comment by carandraug** [comment]
I was expecting something like that (which is why being able to download the submissions is important --- see the other issue #3327 about being unable to download the submissions).

I have access to the whole system including the underlying postgres database. I have even previously manually made changes to the CodaLab database (when we migrated our own MinIO instance). I can upload and change stuff at that level. But for this task I will need directions from someone that is more familiar with the internals of CodaLab. Please don't be shy of sending me to those deep levels of CodaLab.
