### ISSUE TITLE
Problems accessing participant submissions and logs

### ISSUE THREAD

**Issue by jspenmar** [codalab/codalab-competitions#3325]
Hi,

We recently started running a [new competition](https://codalab.lisn.upsaclay.fr/competitions/10031).

I'm having problems accessing both the leaderboard csv and the error logs from the participant submissions, as shown in the screenshots below. Is there any setting that needs to be changed? Could it be due to the fact that the leaderboard is anonymous? 

![Screenshot from 2023-02-20 09-25-48](https://user-images.githubusercontent.com/43554262/220068064-fe5305ad-48a8-47a5-8ed6-e03b51486dfe.png)
![Screenshot from 2023-02-20 09-26-27](https://user-images.githubusercontent.com/43554262/220068086-c20e9968-34eb-4529-a3ed-43754113f14a.png)

Kind regards,
Jaime

**Comment by Didayolo** [comment]
Hi,

Indeed I can reproduce the bug. I think it is due to the fact that the leaderboard is anonymous.

**Comment by jspenmar** [comment]
Sorry, missclick when closing the issue. 

Is there any workaround for this? Our competition will be ending in roughly a week. 

Kind regards,
Jaime

**Comment by dtuantran** [comment]
Hi,
It's not a bug. In order to download your leaderboard csv, you have to add yourself as **Admin** of your competition in the **Edit** page. Even you created your competition, you aren't Admin automatically. Other Admins can also access to theses data.
I've added your account into Admins for your competition. Then you can now access to the leaderboard csv.
About the submission logs, you have to uncheck **Results scoring only** to have submission logs.

![image](https://user-images.githubusercontent.com/7440668/235670245-cfdd6ff1-baa2-4fd6-bde3-9675b55b792c.png)

After unchecking this option, you will be able to access to the submission logs.
