### ISSUE TITLE
"Your kernel does not support swap limit capabilities"

### ISSUE THREAD

**Issue by olyerickson** [codalab/codalab-competitions#3341]
For a long-time deployed competition (and a recent clone) deployed at https://codalab.lisn.upsaclay.fr/competitions/11456 we see the follow error message; what is the fix? This competition has worked for years, until now...

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/tmp/codalab/tmp9CRWdV/run/program/score.py", line 21, in 
    import libscores
  File "/tmp/codalab/tmp9CRWdV/run/program/libscores.py", line 35, in 
    from pip import get_installed_distributions as lib
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/opt/conda/lib/python3.9/site-packages/pip/__init__.py)

**Comment by Didayolo** [comment]
I replied to your email, but I put the fix here in case that can help someone in the future.

The problem comes from the fact we have changed the default competition Docker image.

See here for more information: https://groups.google.com/g/codalab-competitions/c/ePhMJKpcDFM/m/NhAXbyNwBgAJ

The fix consists in setting `codalab/codalab-legacy:py2` as the Docker image.
