### ISSUE TITLE
300M limitation of submission file

### ISSUE THREAD

**Issue by huangmozhi9527** [codalab/codalab-competitions#3394]
Hi, I found that the limitation of submission file is 300M when trying to host a competition.
What if I upload more than 300M files? Is there any way to make this limitation bigger, say 600M.
![image](https://github.com/codalab/codalab-competitions/assets/56259310/49be4ca9-037a-4194-9ee7-7b546175c45a)

**Comment by dtuantran** [comment]
Hi @huangmozhi9527 ,

Because our storage resource is limited, by default the max submission size is 300M. If you want to host a competition supporting bigger submission, you can send us a request to info@codalab.org by precising how many participants you will have, what is the max submissions number you expect per participant, how long your competition during, etc.
By considering theses aspects, we will discuss between our team for giving the decision.

Regards,
