### ISSUE TITLE
'Results do not correspond to current coco set' AssertionError: Results do not correspond to current coco set-test dev

### ISSUE THREAD

**Issue by malareeqi** [codalab/codalab-competitions#3430]
[person_keypoints_test-dev2017_result.zip](https://github.com/codalab/codalab-competitions/files/12607058/person_keypoints_test-dev2017_result.zip)

Good Evening , I need your help to fix the problem.
The problem is  when I submitted the Json file of the predictions of my model to evaluate on competition for coco2017 -test dev keypoints
it got this error :
Traceback (most recent call last):
File "/tmp/codalab/tmpLfd90m/run/program/run.py", line 70, in
cocoDt=cocoGt.loadRes(resFile)
File "/tmp/codalab/tmpLfd90m/run/program/pycocokp/coco.py", line 304, in loadRes
'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

to test the JSON file generated by my code, i sampled some images from val2017 and tried it and it worked, but when i predicted with test-dev2017 data and uploaded the json file to evaluate my model i got the above error.
 I have attached my  JSON prediction file so please check it, I need your help to fix this issue , thank you so much

**Comment by Didayolo** [comment]
Hi,

This problem is specific to your submission and to the COCO challenge. Therefore, you should seek help from the COCO organizers, or in the competition forum. This Github repository relates to the platform in general. 

By looking at your issue, it seems that you try to submit test set prediction on a phase running the validation set. I think you should stick to making predictions on val2017, but, again, I am not part of this competition organizers or participants, so I may be wrong.

Thank you for your comprehension.

**Comment by malareeqi** [comment]
Thank you so much, I solved the problem 
    On Thursday, September 14, 2023 at 08:03:53 PM GMT+8, Adrien Pavão ***@***.***> wrote:  
 
 


Hi,

This problem is specific to your submission and to the COCO challenge. Therefore, you should seek help from the COCO organizers, or in the competition forum. This Github repository relates to the platform in general.

By looking at your issue, it seems that you try to submit test set prediction on a phase running the validation set. I think you should stick to making predictions on val2017, but, again, I am not part of this competition organizers or participants, so I may be wrong.

Thank you for your comprehension.
