### ISSUE TITLE
Warning: The compute queues are congested, please wait for existing jobs to process before submitting more. Thanks for your patience!

### ISSUE THREAD

**Issue by xhsheng-ustc** [codalab/codalab-competitions#3436]
Hi, Codalab maintainers, it seems that the platform has had some problems.  It seems that computation containers are in the congestion status because the page responds following warnings "Warning: The compute queues are congested, please wait for existing jobs to process before submitting more. Thanks for your patience!". However, it still didn't work after a long time waiting. I would be appreciated it if you'd like to check the platform.

**Comment by Didayolo** [comment]
Indeed, the queue is currently congested. We are working on it.

**Comment by krishnamrith12** [comment]
Hi, 

Thanks for your efforts. By when can we resume the submissions. It seems, the submitted files are not being processed.

**Comment by dtuantran** [comment]
> Thank you for your reply. I am meeting a deadline for a conference. I would appreciate it if you could tell me how long the congestion takes.

Dear,

Yesterday, there were some submissions from some public competitions "running" for 10-15 hours. Therefore, it blocked all our compute worker resources and the accumulated submissions are huge, about 200 submissions waiting for processing for now.
Because we offer a free platform and we don't get profit, then we can't offer you more computational resources. However, you can create your own queue with your own compute worker for your competition, as documented here : https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers
Then, your submissions won't be waiting for others anymore.
Thank you for your comprehension.

Regards,

**Comment by dtuantran** [comment]
The platform's returned back to normal. Our queue is no longer congested.
