### ISSUE TITLE
"Edit Competitions" very slow and loads a huge resource list

### ISSUE THREAD

**Issue by changliu19** [codalab/codalab-competitions#3491]
Hi, 

Thank you for developing the codalab platform. We are holding two competitions on Codalab. 

Now I would like to edit some details of the competitions, but the editing page takes 15 minutes can only load halfway. 

When I check the network inspector, I suprisingly found that the page is loading a very huge resource list that contains not ours resources, and the document goes to 200000+ lines

<img width="1187" alt="image" src="https://github.com/codalab/codalab-competitions/assets/54399045/b580f092-7e4d-4e4f-a8af-d54845d3ff0b">

request URL: https://codalab.lisn.upsaclay.fr/competitions/edit_competition/15094

Can you help to check if this is a error on server side? Thanks!

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `pavao` as admin to your competition so they may access it. 

Unable to open the edit page

2. Please post a link to your competition.

https://codalab.lisn.upsaclay.fr/competitions/edit_competition/15094

**Comment by Didayolo** [comment]
Indeed, the edit menu can be very slow to load. However we have no plan in optimizing it since it is very tricky and we are short on work force.

Note that on [Codabench](https://www.codabench.org/), the modernized version of CodaLab, the editor is fast to load, the overall performance are better and you have new features such as live logs. Codabench is easy to adopt as it is compatible with CodaLab bundles.

Thank you for your comprehension.

**Comment by Didayolo** [comment]
I realize that 15 minutes seems problematic, usually it is more something like 30 seconds. Maybe this is worth investigating.

**Comment by changliu19** [comment]
Thanks for your information! We would definitely consider codabench for future competitions.

But I think the problem is, it seems that the editing page tries to fetch all other user's files, which may take infinite time. I am not sure if this is intended or a bug.

Best,
Liu Chang
________________________________
