### ISSUE TITLE
Team management

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#514]
- Create a team
  - Name it
  - Add members
    - Type in name, press add button
  - Exclusive team?
  - Merge team?
  - Request access to team?

**Comment by ErickWa** [comment]
Need to create a more thorough specification for the dev team.

**Comment by ErickWa** [comment]
Related to Issue #902 - see this spec, as it also pertains to Competitions as well as Worksheets

**Comment by ErickWa** [comment]
User, Group & Worksheet/Competition Permissions Specification










Executive Summary
This document describes desired functionality for Users and Groups on the http://www.codalab.org platform, as well as how they interoperate with worksheets and/or competitions


 
Worksheet Process Flow
This document articulates the desired User, Group, and Worksheet Permissions for the CodaLab Project.  
Begin by reviewing the process flow diagram below:
 
![image](https://cloud.githubusercontent.com/assets/4361560/6544081/04ed63e0-c4f1-11e4-8d20-07364a9a914a.png)

Figure 1: Worksheet ProcessFlow
Users who are new to the platform begin as Anonymous Users [1]. These anonymous users may browse public worksheets, but cannot create their own worksheets, or become members of Groups [3].  To have either of these privileges, they must first become Registered Users [2] via the Sign-Up Process.
 
![image](https://cloud.githubusercontent.com/assets/4361560/6544082/0a73c3c2-c4f1-11e4-864b-d4489997b32f.png)

Figure 2: CodaLab Sign Up sheet
Once users have completed the Sign-Up Process, they now become Registered Users [2] in the system. Registered Users are automatically assigned a Default Worksheet [4], which can be viewed and edited only by them.  As a Registered User progressively modifies and updates their Default Worksheet [4], changes should be auto-saved by the system periodically, or the user may manually save their work (Save button or appropriate keyboard shortcut).
Once the Default Worksheet [4] has been sufficiently developed, a Registered User [2] has three choices: 
 a.) Do nothing, and continue editing the Default Worksheet [4], 
b.) Publish the Default Worksheet [4] for public viewing, and make it a Public Worksheet [6], or 
c.) Create and/or join a Group [3], so that a group of colleagues may privately collaborate on the Team Worksheet [5] amongst themselves.
NOTE: This is a two-step process. First, a Registered User must join a Group, and second, that same Registered User must then publish their Default Worksheet [4] as a Team Worksheet [5].  It is possible for a Registered User to join a Team without publishing their Default Worksheet [4] as a Team Worksheet [5]
Finally, Group Worksheets may also be published or unpublished from public view, just like individual worksheets.
Role-Based Access Controls
The processes as described can be easily supported by the role-based access control model shown below:
 
![image](https://cloud.githubusercontent.com/assets/4361560/6544083/0f9f0104-c4f1-11e4-8e03-2421813c6bb1.png)

Figure 3: Role-based Access Control Model
This Role-based Access Control Model supports all anticipated process flows, such as creating, editing, publishing and deleting worksheets, administering groups and shared worksheets, etc.

**Comment by ErickWa** [comment]
Assigning to Eric C. now that basic spec is in place

**Comment by ErickWa** [comment]
Needs a developer to be assigned.
